version: '2'
services:
  rails:
    image: dukedataservice_server
    volumes_from:
      - localdev
    entrypoint: ['rails']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
      - rabbitmq:rabbitmq.host
    env_file:
      - webapp.env
      - swift.env
      - neo4j.client.env
      - elastic.client.env
      - rabbitmq.client.env
  bundle:
    image: dukedataservice_server
    volumes_from:
      - localdev
    entrypoint: ['bundle']
  rake:
    image: dukedataservice_server
    volumes_from:
      - localdev
    entrypoint: ['rake']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
      - rabbitmq:rabbitmq.host
    env_file:
      - webapp.env
      - swift.env
      - neo4j.client.env
      - elastic.client.env
      - rabbitmq.client.env
  authservice:
    image: dukedataservice_server
    env_file:
      - auth_service.env
      - neo4j.client.env
      - elastic.client.env
      - rabbitmq.client.env
    volumes_from:
      - localdev
    entrypoint: ['rake']
    command: auth_service:duke:create
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
      - rabbitmq:rabbitmq.host
  rspec:
    image: dukedataservice_server
    environment:
      - RAILS_ENV=test
      - OPENID_CLIENT_ID=test
      - OPENID_CLIENT_SECRET=testpass
      - OPENID_URL=http://oit.oauth.edu
    volumes_from:
      - localdev
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
      - rabbitmq:rabbitmq.host
    env_file:
      - webapp.env
      - swift.env
      - neo4j.client.env
      - elastic.client.env
      - rabbitmq.client.env
    entrypoint: ['rspec']
    command: spec
  dredd:
    build: ./docker/builds/dredd
    links:
     - server:dds.host
    volumes:
      - ./docker/builds/dredd/dredd_scripts:/home/dredd_scripts/
      - ./apiary.apib:/home/dredd_scripts/apiary.apib
  apiary:
    build: ./docker/builds/apiary
    volumes_from:
      - localdev
  validateapiary:
    image: dukedataservice_apiary
    volumes_from:
      - localdev
    entrypoint: ['api-blueprint-validator']
    command: api_docs/apiary.apib
  genapiary:
    image: dukedataservice_apiary
    volumes_from:
      - localdev
    entrypoint: ['bin/gen_apiary.sh']
