version: '2'
services:
  localdev:
    #make sure image matches what the root Dockerfile is FROM
    image: ruby:2.6.3-stretch
    command: ['echo','setting up localdev']
    volumes:
      - .:/var/www/app
  server:
    build: .
    env_file:
      - swift.env
      - webapp.env
      - neo4j.client.env
      - elastic.client.env
      - rabbitmq.client.env
    ports:
      - 3001:3000
    volumes_from:
      - localdev
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
      - rabbitmq:rabbitmq.host
  db:
    build: ./docker/builds/db
    env_file:
      - db.env
  neo4j:
    image: neo4j:3.1.6
    ports:
      - '7474:7474'
    env_file:
      - neo4j.server.env
  elasticsearch:
    image: elasticsearch:5.4.3
    ports:
      - '9200:9200'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: elasticsearch -E 'action.auto_create_index=false'
  rabbitmq:
    hostname: rabbitmq.host
    container_name: rabbitmq
    image: rabbitmq:3.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
