# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baa098d5e9d5247a33a58e861ff75f7e22a7c5c96027f39efd12e144f34a31423d3aacf45ab79d2c7196907161ec957cd54352b085371b65a32a0e8acf8894e6
  #the service_id allows this service to identify itself to other services
  service_id: c87de9f2-1690-4523-87dc-6395f665a757
  apiexplorer_id: d492cfba-23ad-4360-a63a-e6511d8fe656
test:
  secret_key_base: 1bad0785035ed0a8c7a81f628583b76af348b42f5ed0b73057d03d5c20df543f0bbbb1dccaae2caa57c517757f1540a6dad5bf97efb529752f9128002587cae7
  service_id: 4bb727e6-5820-41f7-88da-8d6c05b4a2b6
  apiexplorer_id: 64b82547-8f84-4dcc-8d84-72d55b3e78bc

# Do not keep ua_test or production secrets in the repository,
# instead read values from the environment.
ua_test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  service_id: <%= ENV['SERVICE_ID'] %>
  apiexplorer_id: <%= ENV['APIEXPLORER_ID'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  service_id: <%= ENV['SERVICE_ID'] %>
  apiexplorer_id: <%= ENV['APIEXPLORER_ID'] %>
